app:
  resource: "@AppBundle/Controller/"
  type:     annotation
admin_area:
  resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
  prefix: /
_sonata_admin:
  resource: .
  type: sonata_admin
  prefix: /
login:
  path:   /login
  defaults:  { _controller: AppBundle:Security:login }
login_check:
  path:   /login_check
logout:
  path:   /logout
