security:
  providers:
    in_memory:
      memory:
        users:
          annie:
            password: $2y$12$ohUvj/6NUiKoH1j5LqfZV.USZ0mMexHwNGoW5bveOL3/LMji0HdV6
            roles: 'ROLE_USER'
          bernard:
            password: $2y$12$ZnHnc943Tnb3u2KoCC1lne2cDsXHlbiSXYgKcg64sxm.RrDa1ThYC
            roles: 'ROLE_USER'
  encoders:
    Symfony\Component\Security\Core\User\User:
      algorithm: bcrypt
      cost: 12
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: ~
      logout: true
      form_login:
        login_path: login
        check_path: login
        csrf_token_generator: security.csrf.token_manager
  access_control:
    - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/, role: ROLE_USER }
